name: sim
networks:
  sim:
    driver: bridge
services:
  next-app:
    image: ghcr.io/1qh/sim-web:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: '3000'
      SITE_URL: https://sim.noboil.dev
    networks: [sim]
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    depends_on:
      - next-app
    networks: [sim]
